version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.2'
    environment:
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '7000:7000'
  kafka:
    image: 'bitnami/kafka:2.7.0'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
    ports:
      - '9092:9092'
      - '29092:29092'